theme: jekyll-theme-minimal
title: My personal website yuh
description: I can pretend that I know how to code
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: Syntax
    url: syntax
  - title: Example
    url: example
  - title: Resume
    url: assets/files/sample_resume.pdf
  - title: Food
    url: food

